# Basic hyprlock configuration example
general {
    hide_cursor = true #
    immediate_render = true #
}

background {
    path = /path/to/image.png #
    blur_passes = 1 #
}

input-field {
    size = 200, 50
    placeholder_text = <i>Password...</i> #
    check_color = rgb(204, 136, 34) #
    fail_color = rgb(204, 34, 34) #
}
